name: Build

on:
  push:
    branches: [ master, v1.4.x ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout cups-local sources
      uses: actions/checkout@v4
    - name: Update build environment
      run: sudo apt-get update --fix-missing -y
    - name: Install prerequisites
      run: sudo apt-get install -y avahi-daemon cppcheck libavahi-client-dev libgnutls28-dev libjpeg-dev libpam-dev libpng-dev libusb-1.0-0-dev zlib1g-dev
    - name: Checkout libcups3
      uses: actions/checkout@v4
      with:
        repository: OpenPrinting/libcups
        path: libcups
    - name: Configure libcups3
      run: cd libcups; ./configure --enable-debug --disable-shared
    - name: Build/Install libcups3
      run: cd libcups; make && sudo make install
    - name: Checkout PAPPL
      uses: actions/checkout@v4
      with:
        repository: michaelrsweet/pappl
        path: pappl
    - name: Configure PAPPL
      run: cd pappl; ./configure --enable-debug --disable-shared
    - name: Build/Install PAPPL
      run: cd pappl; make && sudo make install
    - name: Configure cups-local
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer
    - name: Build cups-local
      run: make
    - name: Test cups-local
      env:
        ASAN_OPTIONS: leak_check_at_exit=false
      run: make test
    - name: Run Clang Static Analyzer
      run: make CC=clang "GHA_ERROR=::error::" clang
    - name: Run cppcheck
      run: make "GHA_ERROR=::error::" cppcheck

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout PAPPL sources
      uses: actions/checkout@v4
    - name: Install Prerequisites
      run: brew install cppcheck libjpeg libpng libusb openssl@3
    - name: Checkout libcups3
      uses: actions/checkout@v4
      with:
        repository: OpenPrinting/libcups
        path: libcups
    - name: Configure libcups3
      run: cd libcups; ./configure --enable-debug --disable-shared
    - name: Build/Install libcups3
      run: cd libcups; make && sudo make install
    - name: Checkout PAPPL
      uses: actions/checkout@v4
      with:
        repository: michaelrsweet/pappl
        path: pappl
    - name: Configure PAPPL
      run: cd pappl; ./configure --enable-debug --disable-shared
    - name: Build/Install PAPPL
      run: cd pappl; make && sudo make install
    - name: Configure cups-local
      run: ./configure --enable-debug --enable-maintainer --with-sanitizer=address
    - name: Build cups-local
      run: make
    - name: Test cups-local
      run: make test
    - name: Run Clang Static Analyzer
      run: make "GHA_ERROR=::error::" clang
    - name: Run cppcheck
      run: make "GHA_ERROR=::error::" cppcheck
